version = '0.0.2'

[[files."CHANGELOG.md"]]
search = """
## [Unreleased]
"""
replace = """
## [Unreleased]


## [{{new_version}}] - {{utcnow | strftime('%Y-%m-%d')}}
"""

[[files."CHANGELOG.md"]]
search = """
[Unreleased]: https://github.com/labpositiva/docker-latex/compare/{{old_version}}...HEAD
"""
replace = """
[Unreleased]: https://github.com/labpositiva/docker-latex/compare/{{new_version}}...HEAD
[{{new_version}}]: https://github.com/labpositiva/docker-latex/compare/{{old_version}}...{{new_version}}
"""
